### ISSUE TITLE
Remove manual buttons

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_tokens#9]
There are no manuals for now...
<img width="1206" alt="screen shot 2018-06-22 at 13 29 46" src="https://user-images.githubusercontent.com/29431263/41774675-0d3127b4-7621-11e8-95a2-c679a2112042.png">

**Comment by kpobococ** [comment]
Done. FYI, this can be done via admin panel by setting/removing links to the manual

**Comment by VonSub** [comment]
verified
